converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('length/', include('length.urls')),
]

length/urls.py
from django.urls import path
from length import views
app_name = 'length'
urlpatterns = [
    path('convert/', views.convert, name='convert'),
]

length/models.py
from django.db import models

# Create your models here.

length/forms.py
from django import forms
class LengthConverterForm(forms.Form):
    MEASUREMENTS = (
        ('centimetre', 'Centimetre'),
        ('metre', 'Metre'),
        ('mile', 'Mile'),
        ('kilometer', 'KiloMeter'),
    )
    input_unit = forms.ChoiceField(choices=MEASUREMENTS, widget=forms.Select(attrs={'class':'regDropDown'}))
    input_value = forms.DecimalField(decimal_places=3, widget=forms.TextInput(attrs={'class':' inputfield'}))
    output_unit = forms.ChoiceField(choices=MEASUREMENTS, widget=forms.Select(attrs={'class':'regDropDown'}))
    output_value = forms.DecimalField(decimal_places=3, required=False, widget=forms.TextInput(attrs={'class':'outputfield', 'readonly':True}))

length/views.py
from django.shortcuts import render
from length.forms import LengthConverterForm
convert_to_metre = {
    "centimetre": 0.01,
    "metre": 1.0,
    "mile": 1609.34,
    "kilometere":1000
}
convert_from_metre = {
    "centimetre": 100,
    "metre": 1.0,
    "mile": 0.000621371,
    "kilometer":0.0001
}

def convert(request):
    form = LengthConverterForm()
    if request.GET:
        input_unit = request.GET['input_unit']
        input_value = request.GET['input_value']
        output_unit = request.GET['output_unit']

        metres = convert_to_metre[input_unit] * float(input_value)
        output_value = metres * convert_from_metre[output_unit]
        data = {
            "input_unit": input_unit,
            "input_value": input_value,
            "output_unit": output_unit,
            "output_value": round(output_value, 3)
        }
        form = LengthConverterForm(initial=data)
        return render(
            request, "length.html", context={"form": form})
    return render(
        request, "length.html", context={"form": form})

length/templates/length.html
{% load static %}
<html lang="en">
  <head>
    <title>Length Conversion</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    
        <nav class="navbar container-fluid top-nav">
        K0nv3rt3r
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        </nav>
    <form class="form1" action={% url "length:convert" %} method="get">
      <div>
        {{ form.input_unit }}
        {{ form.output_unit }}
      </div>
      <div>
        {{ form.input_value }}
        {{ form.output_value }}
      </div>
      <button type="submit" class=" btn btn-success sbtn">Convert</button>
      <button id="clear" class=" btn btn-danger clearbtn">Clear</button>
   </form>
    

   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>